.\" Copyright 2007 Werner Pantke <gnome-color-chooser@punk-ass-bitch.org>
.\"
.\" This file is licensed under GPL
.TH "GNOME Color Chooser" 1 2007-11-27
.SH NAME
gnome\-color\-chooser \- GTK\+/GNOME desktop appearance customization tool
.SH SYNOPSIS
.B gnome\-color\-chooser
.RI [ options ]
.br
.SH DESCRIPTION
GNOME Color Chooser is an application for customizing the appearance of the
GNOME desktop.
.PP
Features:
.br
* change colors and sizes of GTK widgets
.br
* colorize desktop icons
.br
* configure your gtk engines and let your current theme be drawn by
  whatever gtk engine you want
.br
* many more
.BR
.SH OPTIONS
GNOME Color Chooser follows the usual GNU command line syntax, with long options starting
with two dashes (`-'). A summary of options is included below.
.TP
.B \-?
.TP
.B \-\-help
Show a summary of options.
.TP
.B \-\-version
Show GNOME Color Chooser's version.
.TP
Other standard GTK\+/GNOME options not listed here are also supported.
.SH SEE ALSO
http://www.punk-ass-bitch.org/gnome-color-chooser/
.SH AUTHOR
This manual page was written by
.br
Werner Pantke <gnome-color-chooser@punk-ass-bitch.org> .