.\" GNOME Color Chooser - GTK+/GNOME desktop appearance customization tool
.\" Copyright (C) 2007-2008 Werner Pantke <wpantke@punk-ass-bitch.org>
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Project email: <gnome-color-chooser@punk-ass-bitch.org>
.\"
.TH "GNOME Color Chooser" 1 2007-11-27
.SH NAME
gnome\-color\-chooser \- GTK\+/GNOME desktop appearance customization tool
.SH SYNOPSIS
.B gnome\-color\-chooser
.RI [ options ]
.br
.SH DESCRIPTION
GNOME Color Chooser is an application for customizing the appearance of the
GNOME desktop.
.PP
Features:
.br
* change colors and sizes of GTK widgets
.br
* colorize desktop icons
.br
* configure installed gtk engines and let your current theme be drawn
  by a gtk engine you want
.BR
.SH OPTIONS
GNOME Color Chooser follows the usual GNU command line syntax, with long options starting
with two dashes (`-'). A summary of options is included below.
.TP
.B \-?
.TP
.B \-\-help
Show a summary of options.
.TP
.B \-\-version
Show GNOME Color Chooser's version.
.TP
Other standard GTK\+/GNOME options not listed here are also supported.
.SH SEE ALSO
http://www.punk-ass-bitch.org/gnome-color-chooser/
.SH AUTHOR
This manual page was written by
.br
Werner Pantke <gnome-color-chooser@punk-ass-bitch.org> .
